### ISSUE TITLE
Facilities 화면 만들기

### ISSUE THREAD

**Issue by Gahyeon19** [jooYeonIya/JJHOTEL#11]
## Description

- Facilities  화면에서 스크롤 위치에 따라 Dining / Pool의 배경 이미지 & 설명 변경하기

## Tasks

- [x] Dining / Pool 배경 이미지 추가
- [x] Dining / Pool 설명 텍스트 추가
- [x] 스크롤 위치에 따라 Dining과 Pool 변경하기
