### ISSUE TITLE
Reservation 화면에 인원 부분 추가

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/JJHOTEL#14]
## Description

- 인원 타이틀과 플러스 마이너스 버튼 추가하기

## Tasks

- [x] 인원 타이틀 추가
- [x] 플러스, 마이너스 버튼 추가
- [x] 버튼을 클릭했을 때 인원 수 변경
