### ISSUE TITLE
Rooms 페이지 만들기

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/JJHOTEL#15]
## Description

- Rooms 화면과 Reservation 객실 선택 화면에서 사용할 Rooms 페이지를 만듭니다. 
- Rooms 화면에서는 호텔이 보유하고 있는 모든 객실을 표시하고, Reservation 객실 선택 화면에서는 사용자가 입력한 조건에 맞는 객실을 표시합니다.
- RoomList 컴포넌트를 만들어서 Rooms 화면과 Reservation 객실 선택 화면에서 사용합니다.

## Tasks

- [x] Reservation 에서 예약하기 버튼을 클릭했을 때, Header에서 Rooms를 클릭했을 때 Rooms 페이지로 이동하도록 함
- [x] 타이틀 컴포넌트 추가
- [x] 왼쪽 섹션 - 이미지 추가
- [x] 오른쪽 섹션 - 타이틀, 상세보기 버튼, 객실 선택 버튼 추가
