### ISSUE TITLE
RoomDescription 화면 만들기

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/JJHOTEL#16]
## Description

- RoomDescription 화면을 추가합니다

## Tasks

- [x] 상세보기 버튼 클릭 시 화면 이동
- [x] 타이틀 추가
- [x] 메인 이미지 1장, 서브 이미지들 4장 추가하고 서브 이미지들 클릭했을 때 메인 이미지 변경
- [x] 객실 정보, 객실 서비스 불러와서 화면에 표시하기
