### ISSUE TITLE
ReservationInputCustomInfo 화면 만들기

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/JJHOTEL#17]
## Description

- ReservationInputCustomInfo 화면 만들기

## Tasks

- [x] Rooms 페이지에서 객실 선택 버튼 눌렀을 때 화면 이동하도록 함
- [x] 타이틀 추가
- [x] 객실 정보 추가 - 컴포넌트
- [x] 고객 정보 Input 창 추가 - 컴포넌트
- [x] 입력 완료 버튼 추가
