### ISSUE TITLE
Home 화면 만들기

### ISSUE THREAD

**Issue by Gahyeon19** [jooYeonIya/JJHOTEL#22]
## Description

- Main 화면에 All About container 추가

## Tasks

- [x] 메인 이미지 밑에 All About container 만들기
- [x] 각 메뉴에 마우스 오버하면 container 배경 이미지 변경 (처음 이미지는 about 이미지)
- [x] 메뉴 클릭 시 각 화면으로 이동
- [x] map함수 이용하여 코드 단순화
- [x] 마우스 떠났을 때 마지막으로 오버된 이미지 유지
