### ISSUE TITLE
예약확인 화면 만들기

### ISSUE THREAD

**Issue by Gahyeon19** [jooYeonIya/JJHOTEL#24]
## Description

- 헤더에서 예약확인을 눌렀을 때 나오는 예약확인 화면입니다.
- 고객 정보를 입력해야 합니다.
- 고객 정보가 DB에 있는지 확인해야 합니다.
- 일치하면 예약 정보를 보여줍니다.
- 일치하지 않으면 다시 입력하라는 안내창을 띄웁니다.
- 예약 정보란에 예약 취소버튼이 있습니다.

## Tasks

- [x] 고객 정보 입력하는 컴포넌트 추가
- [x] 예약 정보 출력하는 컴포넌트 추가
- [x] 컴포넌트에 입력한 정보와 DB에 저장되어 있는 고객 정보를 비교
- [x] 일치할 경우 화면 아래쪽에 예약정보 띄우기
- [x] 일치하지 않을 경우 Alert 안내창 띄우기
- [x] 예약 정보란에 예약 취소 버튼 만들기
- [x] 예약 취소 버튼 누르면 DB에서 삭제하기
