### ISSUE TITLE
ReservationInputCustomInfo 화면에 DB 정보 불러와서 표시하기

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/JJHOTEL#29]
## Description

- ReservationInputCustomInfo 화면에 DB 정보 불러와서 표시하기

## Tasks

- [x] 객실 타입 Room 테이블에서 RoomName 가져오기
- [x] 날짜 객실 갯수, 인원 ReservaionInfo 객체서 가져오기
- [x] 결제 금액 계산하기 = 객실price * 객실 갯수 * 박수
