### ISSUE TITLE
Header 분리하기

### ISSUE THREAD

**Issue by Gahyeon19** [jooYeonIya/JJHOTEL#36]
## Description

- Header를 각 페이지마다 분리합니다.
- 각 페이지 css 추가합니다.

## Tasks

- [x] Header에 플래그 설정해서 각 페이지마다 다르게 설정
- [x] Facilities / About 페이지 css 파일 추가
- [x] CheckReservation css 파일 추가
