### ISSUE TITLE
RoomDescription 화면 css 추가

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/JJHOTEL#39]
## Description

- RoomDescription 화면 css 추가합니다

## Tasks

- [x] header과 안 겹치게 하기
- [x] 선택 안된 이미지 블러 처리
- [x] 객실 정보 컴포넌트 css 추가
- [x] 객실 서비스 컴포넌트 css 추가
