### ISSUE TITLE
CheckReservation 화면 css 추가

### ISSUE THREAD

**Issue by Gahyeon19** [jooYeonIya/JJHOTEL#40]
## Description

- CheckReservation.css 추가하겠습니다

## Tasks

- [x] 고객 정보 컴포넌트 css 추가
- [x] 예약 정보 컴포넌트 css 추가
- [x] CheckReservation 화면 배경 바꾸기
- [x] 각 컴포넌트에 그림자 추가
