### ISSUE TITLE
전반적인 css 파일 수정

### ISSUE THREAD

**Issue by Gahyeon19** [jooYeonIya/JJHOTEL#44]
## Description

- About화면에서 스크롤 내렸을 때 map 화면이 나오는데 Footer가 보이지 않게 수정하기

## Tasks

- [x] favicon 추가
- [x] 폰트 추가
- [x] Home main 이미지 변경
- [x] Rooms 이미지 추가 + DB 링크 수정
- [x] 텍스트 행간 넓히기, 오타 수정
- [x] (Home 화면 제외) 헤더 밑줄 추가
- [x] 메뉴 마우스 오버 시 메뉴 색깔 변경
