### ISSUE TITLE
수정 사항 

### ISSUE THREAD

**Issue by Gahyeon19** [jooYeonIya/JJHOTEL#47]
## Description

- 어떤 작업을 진행할지 간단하게 내용 작성해주세요.

## Tasks

- [x] 홈 화면에서 예약하기 버튼 누르면 아무것도 안됨
- [x] 인원, 객실 최소 1
- [x] 인원 최대 8 / 객실 최대 10 
- [x] 캘린더에서 인원 초기값2, 객실 초기값1 설정
- [x] 예약할 때 객실 정보에 몇박인지 써놓기
- [x] 예약할 때 이메일 양식 확인하기
- [x] 결제 금액 음수 나옴 (체크인 10월 31일 체크아웃 11월 1일일 때 박수가 음수가 나와서)
- [x] 예약하기 고객 정보 입력 칸 넓히기 
- [x] 예약확인 css 수정(right/left) 
- [x] 파비콘이 나왔다 안나왔다
- [x] 배경색 #f6f1f1으로 수정했으니 다른 컴포넌트들 배경색 수정하기
- [x] 헤더 밑에 밑줄 추가
- [x] About이랑 Facilities 화면에서 헤더 흰색으로 하기
- [x] 객실 정보 가격에 , 쓰기 + size랑 price 앞글자 대문자로 수정
- [x] Reservation에 밑줄 안나오게
- [x] 사진 사이즈 모니터에 맞추기
- [x] 캘린더 반응형으로 수정하기
- [x] aws 연동 (가능하면)
- [x] 발표자료 만들기

**Comment by jooYeonIya** [comment]
aws 연동 은 #63 에서 완료
