### ISSUE TITLE
spring 변경 / 예약 취소하기, 예약 내역 불러오기 수정

### ISSUE THREAD

**Issue by Gahyeon19** [jooYeonIya/JJHOTEL#62]
## Description

- spring으로 변경

## Tasks

- [x] '예약 내역 취소' spring으로 변경 
- [x] '예약 내역 불러오기' isCanceled가 1이면 조회 불가
- [x] '예약 내역 불러오기' 이름과 예약번호 둘 다 비교한 후 예약 내역 가져오기
- [x] 이름과 예약번호 둘 중 하나라도 잘못 입력한 경우 알림창 띄우기
