### ISSUE TITLE
About 화면 만들기 

### ISSUE THREAD

**Issue by Gahyeon19** [jooYeonIya/JJHOTEL#7]
## Description

- About 화면 

## Tasks

- [x] 배경 이미지 삽입
- [x] 설명 텍스트 삽입
- [x] 지도 삽입
- [x] 스크롤에 따라 이미지/지도 보여주기
