### ISSUE TITLE
탈퇴하기 기능 추가

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/JJHOTEL#78]
## Description

- 탈퇴하기 기능 추가

## Tasks

- [x] guest 테이블에 isActive 컬럼 추가
- [x] 컬럼 추가에 따른 백엔드 쪽 변경 (true로 넣어줘야할듯)
- [x] 탈퇴하기 버튼 누르면 탈퇴 확인하기
- [x] 한다고 하면 isActive 컬럼을 false로 변경하기
- [x] 예약 내역이 남아 있으면 탈퇴하지 못 하게 함
- [x] 로그인할 때 탈퇴된 회원은 로그인 못 하도록 변경

**Comment by jooYeonIya** [comment]
> ## Description
> * 탈퇴하기 기능 추가
> 
> ## Tasks
> * [x]  guest 테이블에 isActive 컬럼 추가
> * [x]  컬럼 추가에 따른 백엔드 쪽 변경 (true로 넣어줘야할듯)
> * [x]  탈퇴하기 버튼 누르면 탈퇴 확인하기
> * [x]  한다고 하면 isActive 컬럼을 false로 변경하기
> * [ ]  예약 내역이 남아 있으면 탈퇴하지 못 하게 함
> * [ ]  로그인할 때 탈퇴된 회원은 로그인 못 하도록 변경
