### ISSUE TITLE
Spring 변경에 따른 버그 및 AWS 배포에 따른 버그

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/JJHOTEL#82]
## Description

- Spring 변경에 따른 버그를 해결합니다

## Tasks

- [x] 회원가입 후 /login으로 redirection이 안일어남
- [x] rooms에서 상세보기 하면 roomDescription으로 가지는데 빈 화면 뜸
- [x] 예약하기가 오래걸림
- [x] 예약하고 이메일에서 확인시 이용 날짜: 2024-11-14T15:00:00.000Z ~ 2024-11-16T15:00:00.000Z 이렇게 나옴
- [x] 비회원 예약하기하고 예약조회하면 안나옴
- [x] 로그인하고 홈화면 아래 쪽 about, rooms, reservation, facilite 메뉴 누르면 로그인 해제됨
- [x] front 폴더에서 이미지 폴더 삭제
- [x] 로그 프린트 코드 삭제
- [x] 고객 정보 입력 화면에 loading... 표시 삭제 
- [x] about이랑 facilities화면 이미지 주소 변경
- [x] rooms 페이지, 상세보기 페이지 헤더랑 겹침
- [x] 카카오키 넣었는데도 에러 발생 
- [x] 회원가입 화면 404 에러 -> a 태그 안에서 navigate 하고 있어서 에러 발생 -> link to로 바꿔주면 될 듯
- [x] 회원 예약 내역 확인, 회원 취소 내역 확인, 로그아웃 페이지 401 에러 
(세션 관련 페이지 모두 401 에러 -> 로그인 시 세션을 저장해야 하는데 Axios 요청에서 withCredentials: true 를 뺐기 때문에 세션 및 쿠키가 저장되지 않았고 그로 인해 발생하는 에러인 듯 (withCredentials: true 빼야 되는 줄 알았는데 아니었나봄))

**Comment by Gahyeon19** [comment]
카카오 플랫폼에서 도메인 주소 등록해서 해결 (지도 보임)

**Comment by jooYeonIya** [comment]
rooms 페이지, 상세보기 페이지 헤더 일단 흰색 헤더로 변경
